Repository BME-MIT-IET/ivt-ha-2024-chuck-chuck, pull requests merged in 2024-05, with the labels that each got.

#14 extended_gcd.py fixed
  algorithms/maths/extended_gcd.py
  tests/test_maths.py
Labels: bug, Code review

#12 Rsa review
  algorithms/maths/rsa.py
Labels: Code review

#10 "huffman_coding.py" - Code review
  .github/workflows/python-app.yml
  .idea/.gitignore
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/ivt-ha-2024-chuck-chuck.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  algorithms/compression/huffman_coding.py
Labels: Code review

#11 DFA - Code review
  .github/workflows/python-app.yml
  .idea/workspace.xml
  algorithms/automata/dfa.py
Labels: Code review

#9 "kth_smallest.py" - Code review
  .github/workflows/python-app.yml
  algorithms/tree/bst/kth_smallest.py
Labels: Code review

#17 Static analysis
  .scannerwork/.sonar_lock
  .scannerwork/report-task.txt
  doc/Static_Analysis.md
Labels: enhancement

#21 doc about task
  doc/setup_project.md
Labels: documentation

#28 Created Unit Test Report
  doc/Unit_Tests_Report.md
  doc/coverage_after.png
  doc/coverage_before.png
  doc/extended_gcd_bad_tests.jpg
Labels: documentation

#38 Small fix for Huffman BDD test
  tests/features/huffman_coding.feature
  tests/steps/huffman_coding_step.py
Labels: bdd testing

#40 Changed BDD_Testing.md a bit
  doc/BDD_Testing.md
Labels: documentation
